package com.dailyminutes.laundry.customer.repository;

import com.dailyminutes.DailyminutesApplication; // Import the main application class
import com.dailyminutes.laundry.customer.domain.model.CustomerEntity;
import com.dailyminutes.laundry.customer.domain.model.CustomerOrderSummaryEntity;
import com.dailyminutes.laundry.order.domain.model.OrderEntity;
import com.dailyminutes.laundry.order.domain.model.OrderStatus;
import com.dailyminutes.laundry.order.repository.OrderRepository;
import com.dailyminutes.laundry.store.domain.model.StoreEntity;
import com.dailyminutes.laundry.store.repository.StoreRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.Replace;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jdbc.repository.config.EnableJdbcRepositories;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The type Customer order summary repository test.
 */
@DataJdbcTest(excludeAutoConfiguration = DailyminutesApplication.class)
@AutoConfigureTestDatabase(replace = Replace.NONE)
@EnableJdbcRepositories(basePackages = {"com.dailyminutes.laundry.customer.repository",
        "com.dailyminutes.laundry.store.repository",
        "com.dailyminutes.laundry.order.repository"
})
@ComponentScan(basePackages = {"com.dailyminutes.laundry.customer.domain.model",
        "com.dailyminutes.laundry.store.domain.model",
        "com.dailyminutes.laundry.order.domain.model"})
class CustomerOrderSummaryRepositoryTest {

    @Autowired
    private CustomerOrderSummaryRepository customerOrderSummaryRepository;


    @Autowired
    private StoreRepository storeRepository;

    @Autowired
    private CustomerRepository customerRepository;

    @Autowired
    private OrderRepository orderRepository;

    /**
     * The Store.
     */
    StoreEntity store;
    /**
     * The Customer.
     */
    CustomerEntity customer;

    /**
     * The Order.
     */
    OrderEntity order;


    /**
     * Sets .
     */
    @BeforeEach
    void setup() {
        this.store = storeRepository.save(new StoreEntity(null, "Test Store", "123 Main St", "123-456-7890", "test@example.com", null));
        this.customer = customerRepository.save(new CustomerEntity(null, "SUB123", "9876543210", "Jane Doe", "jane@example.com"));
        this.order = orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));

    }

    /**
     * Test save and find customer order summary.
     */
    @Test
    void testSaveAndFindCustomerOrderSummary() {
        // ID is null as it will be auto-generated by the database
        CustomerOrderSummaryEntity summary = new CustomerOrderSummaryEntity(
                null, order.getId(), customer.getId(), LocalDateTime.now(), "PENDING", new BigDecimal("50.00"), store.getId());
        CustomerOrderSummaryEntity savedSummary = customerOrderSummaryRepository.save(summary);

        assertThat(savedSummary).isNotNull();
        assertThat(savedSummary.getId()).isNotNull(); // Assert that ID is now generated
        assertThat(savedSummary.getOrderId()).isEqualTo(order.getId());
        assertThat(savedSummary.getCustomerId()).isEqualTo(customer.getId());

        Optional<CustomerOrderSummaryEntity> foundSummary = customerOrderSummaryRepository.findById(savedSummary.getId());
        assertThat(foundSummary).isPresent();
        assertThat(foundSummary.get().getStatus()).isEqualTo("PENDING");
        assertThat(foundSummary.get().getTotalAmount()).isEqualByComparingTo("50.00");
    }

    /**
     * Test update customer order summary.
     */
    @Test
    void testUpdateCustomerOrderSummary() {
        CustomerOrderSummaryEntity summary = new CustomerOrderSummaryEntity(
                null, order.getId(), customer.getId(), LocalDateTime.now(), "ACCEPTED", new BigDecimal("75.00"), store.getId());
        CustomerOrderSummaryEntity savedSummary = customerOrderSummaryRepository.save(summary);

        savedSummary.setStatus("DELIVERED");
        savedSummary.setTotalAmount(new BigDecimal("70.00"));
        customerOrderSummaryRepository.save(savedSummary);

        Optional<CustomerOrderSummaryEntity> updatedSummary = customerOrderSummaryRepository.findById(savedSummary.getId());
        assertThat(updatedSummary).isPresent();
        assertThat(updatedSummary.get().getStatus()).isEqualTo("DELIVERED");
        assertThat(updatedSummary.get().getTotalAmount()).isEqualByComparingTo("70.00");
    }

    /**
     * Test delete customer order summary.
     */
    @Test
    void testDeleteCustomerOrderSummary() {
        CustomerOrderSummaryEntity summary = new CustomerOrderSummaryEntity(
                null, order.getId(), customer.getId(), LocalDateTime.now(), "CANCELLED", new BigDecimal("20.00"), order.getId());
        CustomerOrderSummaryEntity savedSummary = customerOrderSummaryRepository.save(summary);

        customerOrderSummaryRepository.deleteById(savedSummary.getId());
        Optional<CustomerOrderSummaryEntity> deletedSummary = customerOrderSummaryRepository.findById(savedSummary.getId());
        assertThat(deletedSummary).isNotPresent();
    }

    /**
     * Test find by customer id.
     */
    @Test
    void testFindByCustomerId() {
        OrderEntity order1=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order2=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order3=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        CustomerEntity customer1=customerRepository.save(new CustomerEntity(null, "SUB1234", "8787678687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer2=customerRepository.save(new CustomerEntity(null, "SUB1235", "7687687687", "Jane Doe", "jane@example.com"));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order1.getId(), customer1.getId(), LocalDateTime.now(), "PENDING", new BigDecimal("10.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order2.getId(), customer1.getId(), LocalDateTime.now(), "DELIVERED", new BigDecimal("25.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order3.getId(), customer2.getId(), LocalDateTime.now(), "NEW", new BigDecimal("30.00"), store.getId()));

        List<CustomerOrderSummaryEntity> ordersForCustomer10 = customerOrderSummaryRepository.findByCustomerId(customer1.getId());
        assertThat(ordersForCustomer10).hasSize(2);
        assertThat(ordersForCustomer10.stream().allMatch(s -> s.getCustomerId().equals(customer1.getId()))).isTrue();
    }

    /**
     * Test find by status.
     */
    @Test
    void testFindByStatus() {
        OrderEntity order1=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order2=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order3=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        CustomerEntity customer1=customerRepository.save(new CustomerEntity(null, "SUB1234", "8787678687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer2=customerRepository.save(new CustomerEntity(null, "SUB1235", "7687687687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer3=customerRepository.save(new CustomerEntity(null, "SUB1236", "7688787687", "Jane Doe", "jane@example.com"));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order1.getId(), customer1.getId(), LocalDateTime.now(), "NEW", new BigDecimal("15.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order2.getId(), customer2.getId(), LocalDateTime.now(), "NEW", new BigDecimal("18.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order3.getId(), customer3.getId(), LocalDateTime.now(), "ACCEPTED", new BigDecimal("22.00"), store.getId()));

        List<CustomerOrderSummaryEntity> newOrders = customerOrderSummaryRepository.findByStatus("NEW");
        assertThat(newOrders).hasSize(2);
        assertThat(newOrders.stream().allMatch(s -> s.getStatus().equals("NEW"))).isTrue();
    }

    /**
     * Test find by store id.
     */
    @Test
    void testFindByStoreId() {
        OrderEntity order1=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order2=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order3=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        CustomerEntity customer1=customerRepository.save(new CustomerEntity(null, "SUB1234", "8787678687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer2=customerRepository.save(new CustomerEntity(null, "SUB1235", "7687687687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer3=customerRepository.save(new CustomerEntity(null, "SUB1236", "7688787687", "Jane Doe", "jane@example.com"));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order1.getId(), customer1.getId(), LocalDateTime.now(), "PENDING", new BigDecimal("100.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order2.getId(), customer2.getId(), LocalDateTime.now(), "DELIVERED", new BigDecimal("120.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order3.getId(), customer3.getId(), LocalDateTime.now(), "ACCEPTED", new BigDecimal("80.00"), store.getId()));

        List<CustomerOrderSummaryEntity> ordersForStore40 = customerOrderSummaryRepository.findByStoreId(store.getId());
        assertThat(ordersForStore40).hasSize(3);
        assertThat(ordersForStore40.stream().allMatch(s -> s.getStoreId().equals(store.getId()))).isTrue();
    }

    /**
     * Test find by order id.
     */
    @Test
    void testFindByOrderId() {
        OrderEntity order1=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        OrderEntity order2=orderRepository.save(new OrderEntity(null, store.getId(), customer.getId(), LocalDateTime.now(), OrderStatus.PENDING, new BigDecimal("25.50")));
        CustomerEntity customer1=customerRepository.save(new CustomerEntity(null, "SUB1234", "8787678687", "Jane Doe", "jane@example.com"));
        CustomerEntity customer2=customerRepository.save(new CustomerEntity(null, "SUB1235", "7687687687", "Jane Doe", "jane@example.com"));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order1.getId(), customer1.getId(), LocalDateTime.now(), "PENDING", new BigDecimal("60.00"), store.getId()));
        customerOrderSummaryRepository.save(new CustomerOrderSummaryEntity(null, order2.getId(), customer2.getId(), LocalDateTime.now(), "DELIVERED", new BigDecimal("70.00"), store.getId()));

        Optional<CustomerOrderSummaryEntity> foundSummary = customerOrderSummaryRepository.findByOrderId(order1.getId());
        assertThat(foundSummary).isPresent();
        assertThat(foundSummary.get().getCustomerId()).isEqualTo(customer1.getId());
    }
}
