package com.chitchatfm.dailyminutes.laundry.agent.repository;

import com.chitchatfm.dailyminutes.DailyminutesApplication; // Import the main application class
import com.chitchatfm.dailyminutes.laundry.agent.domain.model.AgentDesignation;
import com.chitchatfm.dailyminutes.laundry.agent.domain.model.AgentEntity;
import com.chitchatfm.dailyminutes.laundry.agent.domain.model.AgentState;
import com.chitchatfm.dailyminutes.laundry.agent.domain.model.AgentTeamSummaryEntity;
import com.chitchatfm.dailyminutes.laundry.team.domain.model.TeamEntity;
import com.chitchatfm.dailyminutes.laundry.team.domain.model.TeamRole;
import com.chitchatfm.dailyminutes.laundry.team.repository.TeamRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.Replace;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jdbc.repository.config.EnableJdbcRepositories;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The type Agent team summary repository test.
 */
@DataJdbcTest(excludeAutoConfiguration = DailyminutesApplication.class)
@AutoConfigureTestDatabase(replace = Replace.NONE)
@EnableJdbcRepositories(basePackages = {"com.chitchatfm.dailyminutes.laundry.agent.repository",
        "com.chitchatfm.dailyminutes.laundry.team.repository"})
@ComponentScan(basePackages = {"com.chitchatfm.dailyminutes.laundry.agent.domain.model",
        "com.chitchatfm.dailyminutes.laundry.agent.domain.model"})
class AgentTeamSummaryRepositoryTest {

    @Autowired
    private AgentTeamSummaryRepository agentTeamSummaryRepository;

    @Autowired
    private TeamRepository teamRepository;

    @Autowired
    private AgentRepository agentRepository;

    /**
     * The Team.
     */
    TeamEntity team;
    /**
     * The Agent.
     */
    AgentEntity agent;

    /**
     * Setup.
     */
    @BeforeEach
    void setup(){
        this.team = teamRepository.save(new TeamEntity(null, "Fleet Team X", "Vehicle management", TeamRole.FLEET));
        this.agent = agentRepository.save(new AgentEntity(null, "Agent Alpha", AgentState.ACTIVE, team.getId(), "9876543210", "A001", LocalDate.now(), null, AgentDesignation.FLEET_AGENT)); // Updated
    }

    /**
     * Test save and find agent team summary.
     */
    @Test
    void testSaveAndFindAgentTeamSummary() {
        // ID is null as it will be auto-generated by the database
        AgentTeamSummaryEntity summary = new AgentTeamSummaryEntity(null, agent.getId(), team.getId(), "Fleet Alpha", "Team managing fleet agents for Agent 1");
        AgentTeamSummaryEntity savedSummary = agentTeamSummaryRepository.save(summary);

        assertThat(savedSummary).isNotNull();
        assertThat(savedSummary.getId()).isNotNull(); // Assert that ID is now generated
        assertThat(savedSummary.getTeamId()).isEqualTo(team.getId());
        assertThat(savedSummary.getAgentId()).isEqualTo(agent.getTeamId());

        Optional<AgentTeamSummaryEntity> foundSummary = agentTeamSummaryRepository.findById(savedSummary.getId());
        assertThat(foundSummary).isPresent();
        assertThat(foundSummary.get().getTeamName()).isEqualTo("Fleet Alpha");
        assertThat(foundSummary.get().getAgentId()).isEqualTo(agent.getTeamId());
    }

    /**
     * Test update agent team summary.
     */
    @Test
    void testUpdateAgentTeamSummary() {
        AgentTeamSummaryEntity summary = new AgentTeamSummaryEntity(null, agent.getId(), team.getId(), "Ops Beta", "Team handling operations for Agent 2");
        AgentTeamSummaryEntity savedSummary = agentTeamSummaryRepository.save(summary);

        AgentTeamSummaryEntity foundSummary = agentTeamSummaryRepository.findById(savedSummary.getId()).orElseThrow();
        foundSummary.setTeamDescription("Updated description for Ops Beta and Agent 2");
        foundSummary.setTeamName("Ops Beta - Modified");
        agentTeamSummaryRepository.save(foundSummary);

        Optional<AgentTeamSummaryEntity> updatedSummary = agentTeamSummaryRepository.findById(savedSummary.getId());
        assertThat(updatedSummary).isPresent();
        assertThat(updatedSummary.get().getTeamDescription()).isEqualTo("Updated description for Ops Beta and Agent 2");
        assertThat(updatedSummary.get().getTeamName()).isEqualTo("Ops Beta - Modified");
    }

    /**
     * Test delete agent team summary.
     */
    @Test
    void testDeleteAgentTeamSummary() {
        AgentTeamSummaryEntity summary = new AgentTeamSummaryEntity(null, agent.getId(), team.getId(), "Support Gamma", "Customer support team for Agent 3");
        AgentTeamSummaryEntity savedSummary = agentTeamSummaryRepository.save(summary);

        agentTeamSummaryRepository.deleteById(savedSummary.getId());
        Optional<AgentTeamSummaryEntity> deletedSummary = agentTeamSummaryRepository.findById(savedSummary.getId());
        assertThat(deletedSummary).isNotPresent();
    }

    /**
     * Test find by team name.
     */
    @Test
    void testFindByTeamName() {
        agentTeamSummaryRepository.save(new AgentTeamSummaryEntity(null, agent.getId(), team.getId(), "Unique Team Name", "A very unique team for Agent 4"));
        Optional<AgentTeamSummaryEntity> foundSummary = agentTeamSummaryRepository.findByTeamName("Unique Team Name");
        assertThat(foundSummary).isPresent();
        assertThat(foundSummary.get().getTeamId()).isEqualTo(team.getId());
        assertThat(foundSummary.get().getAgentId()).isEqualTo(agent.getTeamId());
    }

    /**
     * Test find by agent id.
     */
    @Test
    void testFindByAgentId() {
        // Agent 5 belongs to Team 105
        AgentEntity agent1 = agentRepository.save(new AgentEntity(null, "Agent Alpha", AgentState.ACTIVE, team.getId(), "876876868", "A003", LocalDate.now(), null, AgentDesignation.FLEET_AGENT)); // Updated
        AgentEntity agent2 = agentRepository.save(new AgentEntity(null, "Agent Beta", AgentState.ACTIVE, team.getId(), "987987987", "A004", LocalDate.now(), null, AgentDesignation.FLEET_AGENT)); // Updated
        AgentEntity agent3 = agentRepository.save(new AgentEntity(null, "Agent Sigma", AgentState.ACTIVE, team.getId(), "5435345345", "A005", LocalDate.now(), null, AgentDesignation.FLEET_AGENT)); // Updated

        TeamEntity team1 = teamRepository.save(new TeamEntity(null, "Fleet Team X1", "Vehicle management1", TeamRole.FLEET));
        TeamEntity team2 = teamRepository.save(new TeamEntity(null, "Fleet Team X2", "Vehicle management2", TeamRole.FLEET));
        TeamEntity team3 = teamRepository.save(new TeamEntity(null, "Fleet Team X3", "Vehicle management3", TeamRole.FLEET));

        agentTeamSummaryRepository.save(new AgentTeamSummaryEntity(null, agent1.getId(), team1.getId(), "Fleet Delta", "Team for Agent 5"));
        // Agent 6 also belongs to Team 105 (if this is a many-to-many or historical view)
        agentTeamSummaryRepository.save(new AgentTeamSummaryEntity(null, agent2.getId(), team2.getId(), "Fleet Delta", "Team for Agent 6"));
        // Agent 7 belongs to Team 106
        agentTeamSummaryRepository.save(new AgentTeamSummaryEntity(null, agent3.getId(), team3.getId(), "Ops Epsilon", "Team for Agent 7"));

        List<AgentTeamSummaryEntity> summariesForAgent5 = agentTeamSummaryRepository.findByAgentId(agent1.getId());
        assertThat(summariesForAgent5).hasSize(1);
        assertThat(summariesForAgent5.get(0).getTeamId()).isEqualTo(team1.getId());

        List<AgentTeamSummaryEntity> summariesForAgent6 = agentTeamSummaryRepository.findByAgentId(agent3.getId());
        assertThat(summariesForAgent6).hasSize(1);
        assertThat(summariesForAgent6.get(0).getTeamId()).isEqualTo(team3.getId());
    }
}
