package com.chitchatfm.dailyminutes.laundry.customer.repository;

import com.chitchatfm.dailyminutes.laundry.customer.domain.model.CustomerEntity;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.Replace;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jdbc.repository.config.EnableJdbcRepositories;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The type Customer repository test.
 */
@DataJdbcTest
@AutoConfigureTestDatabase(replace = Replace.NONE)
@EnableJdbcRepositories(basePackages = "com.chitchatfm.dailyminutes.laundry.customer.repository")
@ComponentScan(basePackages = "com.chitchatfm.dailyminutes.laundry.customer.domain.model")
class CustomerRepositoryTest {

    @Autowired
    private CustomerRepository customerRepository;

    /**
     * Test save and find customer.
     */
    @Test
    void testSaveAndFindCustomer() {
        // Pass null for ID, as it's auto-generated by the database
        CustomerEntity customer = new CustomerEntity(null, "SUB123", "9876543210", "Jane Doe", "jane@example.com");
        CustomerEntity savedCustomer = customerRepository.save(customer);

        assertThat(savedCustomer).isNotNull();
        assertThat(savedCustomer.getId()).isNotNull(); // Assert that ID is now generated

        Optional<CustomerEntity> foundCustomer = customerRepository.findById(savedCustomer.getId());
        assertThat(foundCustomer).isPresent();
        assertThat(foundCustomer.get().getName()).isEqualTo("Jane Doe");
        assertThat(foundCustomer.get().getSubscriberId()).isEqualTo("SUB123");
        assertThat(foundCustomer.get().getPhoneNumber()).isEqualTo("9876543210");
    }

    /**
     * Test update customer.
     */
    @Test
    void testUpdateCustomer() {
        CustomerEntity customer = new CustomerEntity(null, "SUB456", "1112223333", "John Smith", "john@example.com");
        CustomerEntity savedCustomer = customerRepository.save(customer); // Save to get generated ID

        CustomerEntity foundCustomer = customerRepository.findById(savedCustomer.getId()).orElseThrow();
        foundCustomer.setEmail("john.new@example.com");
        customerRepository.save(foundCustomer);

        Optional<CustomerEntity> updatedCustomer = customerRepository.findById(savedCustomer.getId());
        assertThat(updatedCustomer).isPresent();
        assertThat(updatedCustomer.get().getEmail()).isEqualTo("john.new@example.com");
    }

    /**
     * Test delete customer.
     */
    @Test
    void testDeleteCustomer() {
        CustomerEntity customer = new CustomerEntity(null, "SUB789", "4445556666", "Test Delete", "delete@example.com");
        CustomerEntity savedCustomer = customerRepository.save(customer); // Save to get generated ID

        customerRepository.deleteById(savedCustomer.getId());
        Optional<CustomerEntity> deletedCustomer = customerRepository.findById(savedCustomer.getId());
        assertThat(deletedCustomer).isNotPresent();
    }

    /**
     * Test find by subscriber id.
     */
    @Test
    void testFindBySubscriberId() {
        CustomerEntity customer1 = new CustomerEntity(null, "SUB_A", "7778889999", "Customer A", "a@test.com");
        CustomerEntity customer2 = new CustomerEntity(null, "SUB_B", "0001112222", "Customer B", "b@test.com");
        customerRepository.save(customer1);
        customerRepository.save(customer2);

        Optional<CustomerEntity> foundCustomer = customerRepository.findBySubscriberId("SUB_A");
        assertThat(foundCustomer).isPresent();
        assertThat(foundCustomer.get().getName()).isEqualTo("Customer A");
    }

    /**
     * Test find by email.
     */
    @Test
    void testFindByEmail() {
        CustomerEntity customer1 = new CustomerEntity(null, "SUB_C", "5556667777", "Customer C", "c@test.com");
        CustomerEntity customer2 = new CustomerEntity(null, "SUB_D", "8889990000", "Customer D", "d@test.com");
        customerRepository.save(customer1);
        customerRepository.save(customer2);

        Optional<CustomerEntity> foundCustomer = customerRepository.findByEmail("c@test.com");
        assertThat(foundCustomer).isPresent();
        assertThat(foundCustomer.get().getName()).isEqualTo("Customer C");
    }

    /**
     * Test find by phone number.
     */
    @Test
    void testFindByPhoneNumber() {
        CustomerEntity customer1 = new CustomerEntity(null, "SUB_E", "9998887777", "Customer E", "e@test.com");
        CustomerEntity customer2 = new CustomerEntity(null, "SUB_F", "6665554444", "Customer F", "f@test.com");
        customerRepository.save(customer1);
        customerRepository.save(customer2);

        Optional<CustomerEntity> foundCustomer = customerRepository.findByPhoneNumber("9998887777");
        assertThat(foundCustomer).isPresent();
        assertThat(foundCustomer.get().getName()).isEqualTo("Customer E");
    }
}
